"""Prints the max px any element overflows its parent's right edge (headless Chromium, 1280x800).

Generated by atobar-flow; do not edit.
"""

import pathlib
import sys

from playwright.sync_api import sync_playwright

JS = """() => {
  let worst = 0;
  for (const el of document.querySelectorAll('body *')) {
    const p = el.parentElement;
    if (!p || p === document.body) continue;
    const over = el.getBoundingClientRect().right - p.getBoundingClientRect().right;
    if (over > worst) worst = over;
  }
  return Math.ceil(worst);
}"""

with sync_playwright() as pw:
    browser = pw.chromium.launch()
    page = browser.new_page(viewport={"width": 1280, "height": 800})
    page.goto(pathlib.Path(sys.argv[1]).resolve().as_uri())
    print(float(page.evaluate(JS)))
    browser.close()
