#!/usr/bin/env bash
# Prints passed/total from a JUnit run of tests/. Generated by atobar-flow; do not edit.
set -uo pipefail
pytest tests/ -q --junitxml=/tmp/flow-junit.xml >&2 || true
python - <<'PY'
import xml.etree.ElementTree as ET
root = ET.parse("/tmp/flow-junit.xml").getroot()
suites = [root] if root.tag == "testsuite" else list(root)
total = sum(int(s.get("tests", 0)) for s in suites)
bad = sum(int(s.get("failures", 0)) + int(s.get("errors", 0)) for s in suites)
skipped = sum(int(s.get("skipped", 0)) for s in suites)
run = total - skipped
print(0.0 if run <= 0 else (run - bad) / run)
PY
